language: bash
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libwxbase2.8-0
    - libwxgtk2.8-0
    - bc
    - libssl-dev
env:
  global:
  - ELIXIR_VERSION=1.4.0 ERLANG_VERSION=19.0
before_install:
- wget https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_$ERLANG_VERSION-1~ubuntu~trusty_amd64.deb;
- sudo dpkg -i esl-erlang_$ERLANG_VERSION-1~ubuntu~trusty_amd64.deb;
- wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
- unzip -d elixir Precompiled.zip
before_script:
- export PATH=`pwd`/elixir/bin:$PATH
script:
- mix local.hex --force
- mix local.rebar --force
- mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez
  --force
- elixir generate_makefile.exs
- make travis_test
